name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: release tag
        required: true

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.tag }}"
      - run: ls && pwd