name: Release

env:
  CURL_TAG: -d '{"tag_name":"${{ github.event.inputs.tag }}"}'


on:
  release:
    types: [published]

jobs:
  build-apple-x86:
    runs-on: macos-11
    steps:
      - run: echo ${{ github.event }}
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.tag }}"
      - run: rustup target add x86_64-apple-darwin
      - run: cargo build --release --target x86_64-apple-darwin
      - run: |
          curl --request POST \
          --url https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=x86_64-apple-darwin \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/octet-stream' \
          --data-binary "@./target/x86_64-apple-darwin/release/cli" \
          --fail
