name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: release tag
        required: true

jobs:
  build-apple-x86:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.tag }}"
      - run: cargo build --release --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-apple-darwin
          path: ./target/x86_64-apple-darwin/release/cli
  build-apple-aarch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.tag }}"
      - run: cargo build --release --target aarch64-apple-darwin
      - uses: actions/upload-artifact@v2
        with:
          name: aarch64-apple-darwin
          path: ./target/aarch64-apple-darwin/release/cli
  build-linux-x86:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.tag }}"
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: ./target/x86_64-unknown-linux-gnu/release/cli
